In [1]:
import pandas as pd

In [2]:
pd.read_csv("./data_download/slr.csv")

,accepted_taxon_key,order_name,family_name,genus_name,search_species_name,gbif_species_name,confidence,status,match_type,rank,source
0,-1,Lepidoptera,Noctuidae,Agrotis,Agrotis spinifera,NotAvail,98,ACCEPTED,HIGHERRANK,GENUS,london31May2023
1,1770880,Lepidoptera,Noctuidae,Agrotis,Agrotis vestigialis,Agrotis vestigialis,99,ACCEPTED,EXACT,SPECIES,london31May2023
2,1787610,Lepidoptera,Noctuidae,Hadena,Hadena perplexa,Hadena perplexa,99,ACCEPTED,EXACT,SPECIES,london31May2023
3,1789086,Lepidoptera,Noctuidae,Hecatera,Hecatera bicolorata,Hecatera bicolorata,99,ACCEPTED,EXACT,SPECIES,london31May2023
4,1789076,Lepidoptera,Noctuidae,Hecatera,Hecatera dysodea,Hecatera dysodea,99,ACCEPTED,EXACT,SPECIES,london31May2023
...,...,...,...,...,...,...,...,...,...,...,...
189,5112283,Lepidoptera,Noctuidae,Xestia,Xestia xanthographa,Xestia xanthographa,99,ACCEPTED,EXACT,SPECIES,london31May2023
190,1790364,Lepidoptera,Noctuidae,Xylena,Xylena exsoleta,Xylena exsoleta,99,ACCEPTED,EXACT,SPECIES,london31May2023
191,9174377,Lepidoptera,Noctuidae,Xylena,Xylena solidaginis,Xylena solidaginis,99,ACCEPTED,EXACT,SPECIES,london31May2023
192,1790361,Lepidoptera,Noctuidae,Xylena,Xylena vetusta,Xylena vetusta,99,ACCEPTED,EXACT,SPECIES,london31May2023
193,1768150,Lepidoptera,Noctuidae,Xylocampa,Xylocampa areola,Xylocampa areola,99,ACCEPTED,EXACT,SPECIES,london31May2023